[project]
package_dir={"wgpu_native_installer": "package"}
package_data={"wgpu_native_installer": ["**/*.py", "**/*.pyi"]}
authors = [{name = "Asher Jingkong Chen"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "google-re2 == 1.1",
  "httpx == 0.27.0",
  "stream-unzip == 0.0.91",
]
description = "Install wgpu-native"
license = {file = "LICENSE"}
name = "wgpu-native-installer"
packages = ["wgpu_native_installer"]
readme = "README.md"
requires-python = ">= 3.8"
version = "0.0.0"

[project.urls]
Homepage = "https://github.com/AsherJingkongChen/wgpu-native-installer"

[tool.black]
line-length = 80
pyi = true

[tool.pytest.ini_options]
addopts = "-rs"
testpaths = [
  "test/**/*.py",
]
