from argparse import Namespace
from typing import Pattern

def get_asset_name_pattern(arguments: Namespace) -> Pattern[str]: ...
def get_library_name_pattern(arguments: Namespace) -> Pattern[str]: ...
